version: "3.3"

volumes:
  mysql_data:

services:
  sqldb:
    image: mysql:latest
    container_name: helper-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=helper
      - MYSQL_USER=helper
      - MYSQL_PASSWORD=helper
      - MYSQL_ROOT_PASSWORD=helper
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
  helper:
    image: pmt-hcorp/helper:latest
    container_name: helper-server
    environment:
      - APP_NAME="HCorp Projects"
      - DB_CONNECTION=mysql
      - DB_HOST=sqldb
      - DB_PORT=3306
      - DB_DATABASE=helper
      - DB_USERNAME=helper
      - DB_PASSWORD=helper
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=tech@headsupcorporation.com
      - MAIL_PASSWORD=jjscktfmiwbkuvzx
      - MAIL_ENCRYPTION=tls
      - BROADCAST_DRIVER=pusher
      - PUSHER_APP_ID=1932250
      - PUSHER_APP_KEY=ba05c6630b0fc4bed8eb
      - PUSHER_APP_SECRET=f2f9a64d2c9580fcb916
      - PUSHER_HOST=
      - PUSHER_PORT=443
      - PUSHER_SCHEME=https
      - PUSHER_APP_CLUSTER=ap2
    ports:
      - 80:8000
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pmt-hcorp-phpmyadmin
    environment:
      - PMA_HOST=sqldb
      - PMA_USER=helper
      - PMA_PASSWORD=helper
      - PMA_ABSOLUTE_URI=http://localhost:8080
    ports:
      - 8080:80
    depends_on:
      - sqldb
    restart: "no"
    volumes:
      - /etc/localtime:/etc/localtime
